
- service: name=firewalld
           state=started
  sudo: yes

- firewalld: service=https
             permanent=true
             state=enabled
  sudo: yes
  notify: restart firewalld

- firewalld: service=http
             permanent=true
             state=enabled
  sudo: yes
  notify: restart firewalld
