---
# handlers file for easyredmine

- name: restart nginx
  service: name=nginx
           state=restarted
  sudo: yes

- name: restart firewalld
  service: name=firewalld
           state=restarted
  sudo: yes
