---
# vars file for easyredmine

do_redmine_db_import: True
do_redmine_installer: False

cache_dir: /vagrant/scratch

installer_package_name: easyredmine_package_u2072_d201511101601.zip
installer_package_path: '{{ cache_dir }}/{{ installer_package_name }}'

installer_package_url: 'http://software.apidb.org/source/{{ installer_package_name }}'
  
redmine_db_dump_file: '{{ cache_dir }}/redmine_dump.sql.gz'

redmine_root_dir: /opt/easyredmine

mysql_admin_login: root
mysql_admin_password: j3r4b1nA

redmine_db_service_provider: mysql # or mariadb
redmine_db_name: redmine
redmine_db_host: localhost
redmine_db_user: redmine
redmine_db_password: 'QhAKtwCLGW'
redmine_db_encoding: utf8
redmine_db_port: 3306

redmine_email_addr: mheiges@uga.edu
redmine_email_port: 587

sendmail_path: /usr/sbin/sendmail
sendmail_args: -i -t

_redmine_db_import_file: /tmp/redmine_dump.sql
_redmine_db_import_success: /tmp/redmine_db_import_success
_redmine_install_wrapper: /home/vagrant/install_wrapper